=== rowantamer/XML-Labs/lab3/part1/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2023 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="BuildingNumber">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="6"/>
				<xs:enumeration value="7"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="City">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Alexandria"/>
				<xs:enumeration value="Cairo"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Country">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Egypt"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Region">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Sidi bishr"/>
				<xs:enumeration value="Miami"/>
				<xs:enumeration value="El haram"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Street">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="10 st"/>
				<xs:enumeration value="110 st"/>
				<xs:enumeration value="209 st"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Street"/>
				<xs:element ref="BuildingNumber"/>
				<xs:element ref="Region"/>
				<xs:element ref="City"/>
				<xs:element ref="Country"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="addresses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="email">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="rowan@gmail.com"/>
				<xs:enumeration value="shahd5@gmail.com"/>
				<xs:enumeration value="ali@gmail.com"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="phones"/>
				<xs:element ref="addresses"/>
				<xs:element ref="email"/>
			</xs:sequence>
			<xs:attribute name="isbn" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:byte">
						<xs:enumeration value="1"/>
						<xs:enumeration value="2"/>
						<xs:enumeration value="3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="employee" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Rowan Tamer"/>
				<xs:enumeration value="Shahd Tamer"/>
				<xs:enumeration value="Ali Tamer"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="phone">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_phone">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="home"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="phones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="phone"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="ST_phone">
		<xs:restriction base="xs:int">
			<xs:enumeration value="035287008"/>
			<xs:enumeration value="035288008"/>
			<xs:enumeration value="035287009"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== rowantamer/XML-Labs/lab3/part1/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="./employee.css" ?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/ITI/ITI%20-%20Open%20Source%20Development/XML%20Fundamentals/Lab3/employees%20XSD%20Schema/employee.xsd">
	<employee isbn="1">
		<name>Rowan Tamer</name>
		<phones>
			<phone type="home">035287008</phone>
		</phones>
		<addresses>
			<address>
				<Street>10 st</Street>
				<BuildingNumber>5</BuildingNumber>
				<Region>Sidi bishr</Region>
				<City>Alexandria</City>
				<Country>Egypt</Country>
			</address>
		</addresses>
		<email>rowan@gmail.com</email>
	</employee>
	<employee isbn="2">
			<name>Shahd Tamer</name>
		<phones>
			<phone type="home">035288008</phone>
		</phones>
		<addresses>
			<address>
				<Street>110 st</Street>
				<BuildingNumber>5</BuildingNumber>
				<Region>Miami</Region>
				<City>Alexandria</City>
				<Country>Egypt</Country>
			</address>
		</addresses>
		<email>shahd5@gmail.com</email>
	</employee>
	<employee isbn="3">
		<name>Ali Tamer</name>
		<phones>
			<phone type="home">035287009</phone>
		</phones>
		<addresses>
			<address>
				<Street>209 st</Street>
				<BuildingNumber>5</BuildingNumber>
				<Region>El haram</Region>
				<City>Cairo</City>
				<Country>Egypt</Country>
			</address>
		</addresses>
		<email>ali@gmail.com</email>
	</employee>
</employees>
